target 'YouGotaGiftTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouGotaGiftTask
  
    pod 'Alamofire', '~> 5.2'
    pod 'Kingfisher', '~> 5.0'
    #pod 'IQKeyboardManagerSwift'
    
    #pod 'Swift_PageMenu', '~> 1.4'
    
  
end
